version: '3.4'

services:
    app:
        container_name: app
        build:
            context: apps/challenge/.
            target: builder
        command: npm run start:dev
        restart: on-failure
        env_file:
            - ./.envs/.db.env
            - ./.envs/backend.env
        ports:
            - 3000:3000
        volumes:
          - ./apps/challenge/src:/app/src
        depends_on:
          - db-seeder

    db-seeder:
        build: apps/seeder

        container_name: db-seeder
        env_file:
            - ./.envs/.db.env
            - ./.envs/backend.env
        depends_on:
          - database

    database:
        container_name: database
        image: mongo:4.2
        restart: on-failure
        env_file:
            - ./.envs/.db.env
        ports:
          - 27017:27017
        volumes:
            - ./volumes/database:/data/db
