version: '3.4'

services:
    app:
        container_name: app
        build:
            context: apps/backend/.
            target: builder
        command: npm run start:dev
        restart: on-failure
        env_file:
            - .envs/.db.env
        ports:
            - 3000:3000
        volumes:
          - ./apps/backend/src:/app/src

    database:
        container_name: database
        image: mongo:4.2
        restart: on-failure
        env_file:
            - .envs/.db.env
        volumes:
            - ./volumes/database:/data/db
